name: release

on:
  schedule:
    - cron:  '14 20 * * *' # Runs at 20:14 UTC (5:14 JST) every day.
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'reviewdog/reviewdog'
          ref: 'nightly' # TODO(haya14busa): switch to master.

      - run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git tag -a "nightly-$(date +%F)-$(git rev-parse --short HEAD)" -m "nightly release"

      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config=.goreleaser-nightly.yml
